### ISSUE TITLE
NET Framework requirement; Class ambiguities; Quick start guide?

### ISSUE THREAD

**Issue by futurecreep-dev** [wafflesgama/LazyBuilder#1]
I think it needs to be mentioned upfront that it requires .NET Framework (Api Compatibility Level set to .NET Framework in the project settings). Would be nice if there's a solid/easy way to make it compatible with .NET Standard but there's probably not.

Also had an issue with the Skeleton and Node classes as I already had identically named ones implemented by other assets. Easily fixed but has to be pointed out.

But now that I fixed these I don't know where to start. Can't see anything obvious like a quick start, readme, dropdown menu etc. Would appreciate any pointers. Or is this too early in development? What coverage of Sceelix features should be expected?
Thank you.

**Comment by wafflesgama** [comment]
Hi, thank you for the suggestion!  
There is in fact a mini tutorial to get you started, I've updated the Readme with the tutorial+ questionnaire (under Quickstart).
